baseurl = "https://dotlayer.org/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = ".Layer"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
googleAnalytics = "UA-127083360-1"
pluralizeListTitles = false
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

# Enable Emoji emoticons support for page content; see emoji-cheat-sheet.com
enableEmoji   = true

[permalinks]
    blog = "/:slug/"


[params]
  # Sets the meta tag description (duplicated in Languages)
  description          = ".Layer community website"
  
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = ".Layer"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/blog/"
  # Sets default img for thumbnails
  og_image             = "img/main/DotLayer_logo_short_COL_RVB.png"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = true
  rssAppearAtBottom    = true
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # set to show or to hide categories in the sidebar
  showSidebarCategories = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = true
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = true
  faviconVersion       = ""
  faviconPath          = "img/main/dotlayer_favicon.ico"
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Sets specific share to appear on posts (default behavior is to appear)
  socialShareTwitter   = true
  socialShareGoogleplus = false
  socialShareFacebook  = true
  socialShareReddit    = false
  socialShareLinkedin  = true
  socialShareStumbleupon = false
  socialSharePinterest = false
  socialShareEmail     = true

  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["css/add-on.css", "default"]
  customJS             = ["default"]

  # options for highlight.js (version, additional languages, and theme)
  disable_highlight = false # set to true to disable Highlight
  highlightjsVersion = "9.18.1"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml", "css", "julia", "python"]
  highlightjsTheme = "github"
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.1"


[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 0

[params.intro]
  header    = "img/main/DotLayer_logo_full+tagline_COL_RVB.png"
  paragraph = ""

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    # src       = "/img/main/DotLayer_logo_full+tagline_COL_RVB.jpg"
    # Sets Image to be a cirlce
    # circle    = false
    # Sets Image to be Future Imperfect's hexagon
    # imperfect = false
    # width     = "250px"
    # alt       = ".Layer"

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[Languages]
    [Languages.en]
        LanguageName = "English"
        title = ".Layer"
        description = ".Layer community website"
        weight = 1

            # Sets the menu items in the navigation bar
            # Identifier prepends a Font Awesome icon to the menu item
            # Each language has its own menu.
            [[Languages.en.menu.main]]
                name = "Home"
                url = "/"
                identifier = "fa fa-home"
                weight = 1

            [[Languages.en.menu.main]]
                name = "About"
                url = "/about/"
                identifier = "fa fa-info"
                weight = 2

            [[Languages.en.menu.main]]
                name = "Contact"
                url = "/contact/"
                identifier = "fa fa-envelope-o"
                weight = 3

            [[Languages.en.menu.main]]
                name = "Contribute"
                url = "/contribute/"
                identifier = "fa fa-hand-peace-o"
                weight = 4

            [[Languages.en.menu.main]]
                name = "Bookshelf"
                url = "/bookshelf/"
                identifier = "fa fa-book"
                weight = 5
            
            # These are optional params related to the sidebar. They are recommended, but not
            # required for proper functionality. HTML is supported within the params.
            [Languages.en.params.intro]
            about     = ".Layer (dot-layer) is an open community dedicated to promoting collaboration and knowledge sharing in data science. In Unix operating systems, files beggining with a dot are invisible to the user. Many ignore their purpose, even their existence. In this world where data are queens, *data scientists* form this hidden layer, invisible to the public. It is now time we say Hello, World!"
            header    = "img/main/DotLayer_logo_full+tagline_COL_RVB.png"
           
            # This appears at the top of the sidebar above params.intro.header.
            # A width of less than 100px is recommended from a design perspective.
            [Languages.en.params.intro.pic]  # (useless, defined for all languages)
                # src       = "/img/main/logo.jpg"
                # Sets Image to be a cirlce
                # circle    = false
                # Sets Image to be Future Imperfect's hexagon
                # imperfect = true
                # width     = ""
                # alt       = "Hugo Future Imperfect"

    [Languages.fr]
        LanguageName = "Français"
        title = ".Layer"
        description = "Site web de la communauté .Layer"
        weight = 2

            [[Languages.fr.menu.main]]
                name = "Accueil"
                url = "/"
                identifier = "fa fa-home"
                weight = 1

            [[Languages.fr.menu.main]]
                name = "À propos"
                url = "/about/"
                identifier = "fa fa-info"
                weight = 2

            [[Languages.fr.menu.main]]
                name = "Contact"
                url = "/contact/"
                identifier = "fa fa-envelope-o"
                weight = 3
            
            [[Languages.fr.menu.main]]
                name = "Contribuer"
                url = "/contribute/"
                identifier = "fa fa-hand-peace-o"
                weight = 4

            [[Languages.fr.menu.main]]
                name = "Étagère à livres"
                url = "/bookshelf/"
                identifier = "fa fa-book"
                weight = 5

            # These are optional params related to the sidebar. They are recommended, but not
            # required for proper functionality. HTML is supported within the params.
            [Languages.fr.params.intro]
            # paragraph = "Rencontrer, Apprendre & Partager."
            header    = "img/main/DotLayer_logo_full+tagline_COL_RVB.png"
            about     = ".Layer (dot-layer) est une communauté ouverte dédiée à la promotion de la collaboration et le partage de connaissances en science des données. Dans les systèmes d'exploitation Unix, les fichiers et répertoires commençant par un point sont invisibles pour l'utilisateur. Plusieurs ignorent leur rôle et même leur existence. En ce monde où les données sont reines, les *data scientists* forment cette couche cachée, invisible du grand public. Il est maintenant temps que nous disions Hello, World!"

            # This appears at the top of the sidebar above params.intro.header.
            # A width of less than 100px is recommended from a design perspective.
            [Languages.fr.params.intro.pic] # (useless, defined for all languages)
                # src       = "/img/main/logo.jpg"
                # Sets Image to be a cirlce
                # circle    = false
                # Sets Image to be Future Imperfect's hexagon
                # imperfect = true
                # width     = ""
                # alt       = "Hugo Future Imperfect"

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github           = "dot-layer/blog"
  gitlab           = ""
  stackoverflow    = "" # User Number
  bitbucket        = ""
  jsfiddle         = ""
  codepen          = ""
  # Visual Art Communities
  deviantart       = ""
  flickr           = ""
  behance          = ""
  dribbble         = ""
  # Publishing Communities
  wordpress        = ""
  medium           = ""
  # Professional/Business Oriented Communities
  linkedin         = ""
  linkedin_company = ""
  foursquare       = ""
  xing             = ""
  slideshare       = ""
  # Social Networks
  slack            = "dotlayerorg.slack.com"
  facebook         = "groups/dotlayer"
  googleplus       = ""
  reddit           = ""
  quora            = ""
  youtube          = ""
  vimeo            = ""
  whatsapp         = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat         = ""
    qq             = "" # User ID Number
  instagram        = ""
  tumblr           = ""
  twitter          = ""
  skype            = ""
  snapchat         = ""
  pinterest        = ""
  telegram         = ""
  vine             = ""
  googlescholar    = ""
  orcid            = ""
  researchgate     = ""
  # Email
  email            = "info@dotlayer.org"

[markup.goldmark.renderer]
unsafe= true